exports.fakeAddresses = [
 '19, Anthony Road, Street, Somerset, BA16 0AE'  ,
 '9, Anthony Road, Street, Somerset, BA16 0AE'   ,
 ' 6, Bowling Green, Street, Somerset, BA16 0AH' ,
 ' 8, Bowling Green, Street, Somerset, BA16 0AH' ,
 ' 8, Bowling Green, Street, Somerset, BA16 0AH' ,
 '12, Bowling Green, Street, Somerset, BA16 0AH' ,
 'Flat 17, William Reynolds House, Springbok Close, Street, Somerset, BA16 0AL' ,
 'Flat 9, William Reynolds House, Springbok Close, Street, Somerset, BA16 0AL' ,
 '17, Grange Road, Street, Somerset, BA16 0AY'    ,
  '13, Grange Road, Street, Somerset, BA16 0AY'   ,
  '91, Somerton Road, Street, Somerset, BA16 0DN' ,

  'Annexe, 1, Water Street, Langport, Somerset, TA10 0AH' ,
  '1, Water Street, Langport, Somerset, TA10 0AH' ,
  '14, Ham Green, Langport, Somerset, TA10 0AR' ,
  '10, Ham Green, Langport, Somerset, TA10 0AR' ,
  '8, Ham Green, Langport, Somerset, TA10 0AR'  ,
  'Brewers End, Langport, Somerset, TA10 0AZ'   ,

  'The Chantry, Butchers Hill, Taunton, Somerset, TA3 6PD' ,
  'Cornerways, Butchers Hill, Taunton, Somerset, TA3 6PD'  ,
  'Orchard End, Butchers Hill, Taunton, Somerset, TA3 6PDDurborough Cottage, Bridgwater, Somerset, TA5 1AP' ,
  'Brading, Butchers Hill, Taunton, Somerset, TA3 6PD' ,
  'Bridge Cottage, Butchers Hill, Taunton, Somerset, TA3 6PD' ,
  'Mill Mount, Butchers Hill, Taunton, Somerset, TA3 6PD' ,

  'Lilac Cottage, Four Forks Lane, Bridgwater, Somerset, TA5 1AB' ,
  'Goodwill Cottage, Four Forks Lane, Bridgwater, Somerset, TA5 1AB' ,
  '2, Four Forks Lane, Bridgwater, Somerset, TA5 1AB'   ,
  '131, Four Forks Lane, Bridgwater, Somerset, TA5 1AB' ,
  '126, Four Forks Lane, Bridgwater, Somerset, TA5 1AB' ,
  '128, Four Forks Lane, Bridgwater, Somerset, TA5 1AB' ,
  '133, Four Forks Lane, Bridgwater, Somerset, TA5 1AB' ,
  'Brookside, Bridgwater, Somerset, TA5 1AP' ,
  'Higher Aisholt Farm, Bridgwater, Somerset, TA5 1AP' ,
  'Durborough Cottage, Bridgwater, Somerset, TA5 1AP'  ,
  'The Pines, Buncombe Hill, Bridgwater, Somerset, TA5 1AX' ,

  'Triangle House, Frog Lane, Yeovil, Somerset, BA22 7AJ' ,
  'Triangle Cottage, Frog Lane, Yeovil, Somerset, BA22 7AJ' ,
  'Blacksmith Close, Frog Lane, Yeovil, Somerset, BA22 7AJ' ,
  '1, Abbey Cottages, Galhampton Road, Yeovil, Somerset, BA22 7AQ' ,
  'The Coach House, Middle Street, Yeovil, Somerset, BA22 7AP' ,
  'Stoneleigh, Middle Street, Yeovil, Somerset, BA22 7AP' ,
  'Stable Lodge, Middle Street, Yeovil, Somerset, BA22 7AP' ,
  'Old Post Office, Middle Street, Yeovil, Somerset, BA22 7AP'
];
